#!/usr/bin/env python3

KEY_INPUT_FASTA="fasta"
KEY_REFERENCE_FASTA = "reference_fasta"
KEY_TO_MASK = "to_mask"
KEY_GENE_BOUNDARIES = "gene_boundaries"
KEY_OUTDIR = "outdir"
KEY_OUTFILE = "alignment_file"
KEY_CDS_OUTFILE = "cds_outfile"
KEY_CONCATENATE = "concatenate"
KEY_TEMPDIR = "tempdir"
KEY_NO_TEMP="no_temp"
KEY_VERBOSE="verbose"
KEY_THREADS = "threads"
KEY_NO_MASK="no_mask"
KEY_TRIM_END="trim_end"
KEY_EXTRACT_CDS="extract_cds"