name: squirrel
on: [push, pull_request]
defaults:
  run:
    shell: bash -l {0}

jobs:
  run_squirrel_test:
    name: squirrel test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: false
          environment-file: environment.yml
          activate-environment: squirrel
          channels: conda-forge,bioconda,defaults
          miniforge-version: latest
      - name: Install squirrel
        run: pip install -e .
      - name: Check squirrel version
        run: squirrel --version
      - name: Run squirrel with test data
        run: squirrel squirrel/data/NC_063383.fasta 2>&1 | tee squirrel.log
      - name: Run squirrel phylo with test data
        run: squirrel ./test/cI_test.with_og.fasta --clade cladei --run-phylo --outgroups 'JX878419' 2>&1 | tee squirrel_phylo.log
      - name: Run squirrel seq qc with test data
        run: squirrel ./test/cI_test.with_og.fasta --clade cladei  --run-phylo --outgroups 'JX878419' --seq-qc --assembly-refs squirrel/data/ref_seq.fasta 2>&1 | tee squirrel_qc.log
      - name: Run squirrel --include-background with test data
        run: squirrel ./test/cI_test.fasta --clade cladei  --run-phylo --include-background 2>&1 | tee squirrel_bg.log
      - name: Run squirrel --include-background with test data and outdir specified and seqqc
        run: squirrel ./test/cI_test.fasta --clade cladei -o squirrel_output --run-phylo --seq-qc --include-background 2>&1 | tee squirrel_bg.log
      - name: Run squirrel --include-background with test data and outdir specified and seqqc with clade split
        run: squirrel ./test/varied_test.fasta --clade split -o squirrel_output --run-phylo --seq-qc --include-background 2>&1 | tee squirrel_split.log
      - name: Run squirrel variola
        run: squirrel ./test/cI_test.fasta --clade variola -o squirrel_output --run-phylo --seq-qc --include-background 2>&1 | tee squirrel_var.log
